apiVersion: v1
kind: Pod
metadata:
  name: lana-pod
  labels:
    name: lana-pod
spec:
  containers:
  - name: app
    image: busybox
    command: ['sh', '-c', 'counter=1; while true; do touch "/mnt/test-$counter.txt"; counter=$((counter+1));sleep 30; done']
    volumeMounts:
      - name: local-persistent-storage
        mountPath: /mnt
  volumes:
    - name: local-persistent-storage
      persistentVolumeClaim:
        claimName: lana-pvc1

