apiVersion: v1
kind: PersistentVolume
metadata:
  name: alert-manager-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  mountOptions:
    - hard
    - nfsvers=4.0
  nfs:
    path: /var/nfs/k8s
    server: 10.168.0.19
