apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc2
  namespace: docker-registry
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
